---
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }

- hosts: master
  serial: 1
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }