---
- name: Add Kubernetes yum repository
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: Kubernetes
    description: Kubernetes Repository
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no

- name: Install kubernetes packages (RHEL/CentOS)
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ pkgs }}"
    update_cache: yes
    state: installed
  with_items: "{{ pkgs }}"

- name: 使用定制的 kubeadm
  copy: src=kubeadm dest=/usr/bin/kubeadm mode=755
