---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- block:

  - name: Copy kubeadm conf to drop-in directory
    template:
      src: init.config.j2
      dest: "{{ kubeadm_config }}"
      backup: true

  - name: Init Kubernetes cluster
    shell: kubeadm init --config {{ kubeadm_config }} --upload-certs
    register: init_cluster

  when: reset_cluster is succeeded

