---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Copy kubeadm conf to drop-in directory
  template:
    src: kubeadm.config.j2
    dest: "{{ kubeadm_config }}"
    backup: true

- name: Init Kubernetes cluster
  when: reset_cluster is succeeded
  shell: kubeadm init --config {{ kubeadm_config }} --upload-certs --skip-phases addon
  register: init_cluster

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded
  copy:
    src: "{{ admin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0755
    remote_src: true
