---
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- block:

  - name: Get ca cert hash
    shell: openssl x509 -pubkey -in {{ certificates_dir }}/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* /sha256:/'
    delegate_to: "{{ groups.master.0 }}"
    register: caCertHashes
    run_once: yes
    changed_when: false

  - set_fact: caCertHashes={{ caCertHashes.stdout }}
    run_once: yes

  - name: Copy kubeadm conf to drop-in directory
    template:
      src: join.config.j2
      dest: "{{ kubeadm_config }}"
      backup: true

  - name: Join to Kubernetes cluster
    shell: kubeadm join --config {{ kubeadm_config }}
    register: join_cluster

  when: reset_cluster is succeeded

- block:

  - name: Create Kubernetes config directory
    file:
      path: ".kube/"
      state: directory

  - name: Copy admin.conf to Home directory
    copy:
      src: "{{ admin_config }}"
      dest: ".kube/config"
      owner: "{{ ansible_user | default(ansible_user_id) }}"
      group: "{{ ansible_user | default(ansible_user_id) }}"
      mode: 0755
      remote_src: true

  when: join_cluster is succeeded
