---
- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- block:
  - name: Init cluster if needed
    include_tasks: init.yml
    when: groups.master.0 == inventory_hostname
    run_once: yes

  - name: Join cluster if needed
    include_tasks: join.yml
    when: groups.master.0 != inventory_hostname

  - name: Create Kubernetes config directory
    file:
      path: ".kube/"
      state: directory

  - name: Copy admin.conf to Home directory
    copy:
      src: "{{ admin_config }}"
      dest: ".kube/config"
      owner: "{{ ansible_user | default(ansible_user_id) }}"
      group: "{{ ansible_user | default(ansible_user_id) }}"
      mode: 0755
      remote_src: true

  when: not kubeadm_ca.stat.exists
